name: ate-onde-chega-cultura # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The map of cultural equipments in Portugal # 79 char long summary
description: |
  Este é um projeto comunitário do Interruptor inspirado na série Até onde chega
  a cultura?, que explora a distribuição geográfica de diversos equipamentos no
  nosso território para tentar perceber o alcance da cultura. Foi iniciado
  durante o Hacktoberfest 2020.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cultura:
    extensions: [flutter-master]
    command: usr/bin/cultura

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
